[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_forge"

# Compiler settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 2
fuzz_runs = 1000
fuzz_max_test_rejects = 65536

# Gas settings
gas_limit = 12000000
gas_price = 30000000000

# RPC settings
eth_rpc_url = "http://localhost:8545"

# Formatter settings
line_length = 120
tab_width = 4
bracket_spacing = false

[profile.ci]
fuzz_runs = 10000

[profile.lite]
optimizer = false
fuzz_runs = 100